// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/collaboration": {
    params: {};
  };
  "/test": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/projects" | "/blog" | "/contact" | "/collaboration" | "/test";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/collaboration.tsx": {
    id: "routes/collaboration";
    page: "/collaboration";
  };
  "routes/test.tsx": {
    id: "routes/test";
    page: "/test";
  };
};